import { BsFacebook, BsInstagram, BsTwitter } from "react-icons/bs";

export const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands (the)",
  "Central African Republic (the)",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];

export const languages = [
  { code: "ab", name: "Abkhazian" },
  { code: "aa", name: "Afar" },
  { code: "af", name: "Afrikaans" },
  { code: "ak", name: "Akan" },
  { code: "sq", name: "Albanian" },
  { code: "am", name: "Amharic" },
  { code: "ar", name: "Arabic" },
  { code: "an", name: "Aragonese" },
  { code: "hy", name: "Armenian" },
  { code: "as", name: "Assamese" },
  { code: "av", name: "Avaric" },
  { code: "ae", name: "Avestan" },
  { code: "ay", name: "Aymara" },
  { code: "az", name: "Azerbaijani" },
  { code: "bm", name: "Bambara" },
  { code: "ba", name: "Bashkir" },
  { code: "eu", name: "Basque" },
  { code: "be", name: "Belarusian" },
  { code: "bn", name: "Bengali" },
  { code: "bh", name: "Bihari languages" },
  { code: "bi", name: "Bislama" },
  { code: "bs", name: "Bosnian" },
  { code: "br", name: "Breton" },
  { code: "bg", name: "Bulgarian" },
  { code: "my", name: "Burmese" },
  { code: "ca", name: "Catalan, Valencian" },
  { code: "km", name: "Central Khmer" },
  { code: "ch", name: "Chamorro" },
  { code: "ce", name: "Chechen" },
  { code: "ny", name: "Chichewa, Chewa, Nyanja" },
  { code: "zh", name: "Chinese" },
  { code: "cu", name: "Church Slavonic, Old Bulgarian, Old Church Slavonic" },
  { code: "cv", name: "Chuvash" },
  { code: "kw", name: "Cornish" },
  { code: "co", name: "Corsican" },
  { code: "cr", name: "Cree" },
  { code: "hr", name: "Croatian" },
  { code: "cs", name: "Czech" },
  { code: "da", name: "Danish" },
  { code: "dv", name: "Divehi, Dhivehi, Maldivian" },
  { code: "nl", name: "Dutch, Flemish" },
  { code: "dz", name: "Dzongkha" },
  { code: "en", name: "English" },
  { code: "eo", name: "Esperanto" },
  { code: "et", name: "Estonian" },
  { code: "ee", name: "Ewe" },
  { code: "fo", name: "Faroese" },
  { code: "fj", name: "Fijian" },
  { code: "fi", name: "Finnish" },
  { code: "fr", name: "French" },
  { code: "ff", name: "Fulah" },
  { code: "gd", name: "Gaelic, Scottish Gaelic" },
  { code: "gl", name: "Galician" },
  { code: "lg", name: "Ganda" },
  { code: "ka", name: "Georgian" },
  { code: "de", name: "German" },
  { code: "ki", name: "Gikuyu, Kikuyu" },
  { code: "el", name: "Greek (Modern)" },
  { code: "kl", name: "Greenlandic, Kalaallisut" },
  { code: "gn", name: "Guarani" },
  { code: "gu", name: "Gujarati" },
  { code: "ht", name: "Haitian, Haitian Creole" },
  { code: "ha", name: "Hausa" },
  { code: "he", name: "Hebrew" },
  { code: "hz", name: "Herero" },
  { code: "hi", name: "Hindi" },
  { code: "ho", name: "Hiri Motu" },
  { code: "hu", name: "Hungarian" },
  { code: "is", name: "Icelandic" },
  { code: "io", name: "Ido" },
  { code: "ig", name: "Igbo" },
  { code: "id", name: "Indonesian" },
  {
    code: "ia",
    name: "Interlingua (International Auxiliary Language Association)",
  },
  { code: "ie", name: "Interlingue" },
  { code: "iu", name: "Inuktitut" },
  { code: "ik", name: "Inupiaq" },
  { code: "ga", name: "Irish" },
  { code: "it", name: "Italian" },
  { code: "ja", name: "Japanese" },
  { code: "jv", name: "Javanese" },
  { code: "kn", name: "Kannada" },
  { code: "kr", name: "Kanuri" },
  { code: "ks", name: "Kashmiri" },
  { code: "kk", name: "Kazakh" },
  { code: "rw", name: "Kinyarwanda" },
  { code: "kv", name: "Komi" },
  { code: "kg", name: "Kongo" },
  { code: "ko", name: "Korean" },
  { code: "kj", name: "Kwanyama, Kuanyama" },
  { code: "ku", name: "Kurdish" },
  { code: "ky", name: "Kyrgyz" },
  { code: "lo", name: "Lao" },
  { code: "la", name: "Latin" },
  { code: "lv", name: "Latvian" },
  { code: "lb", name: "Letzeburgesch, Luxembourgish" },
  { code: "li", name: "Limburgish, Limburgan, Limburger" },
  { code: "ln", name: "Lingala" },
  { code: "lt", name: "Lithuanian" },
  { code: "lu", name: "Luba-Katanga" },
  { code: "mk", name: "Macedonian" },
  { code: "mg", name: "Malagasy" },
  { code: "ms", name: "Malay" },
  { code: "ml", name: "Malayalam" },
  { code: "mt", name: "Maltese" },
  { code: "gv", name: "Manx" },
  { code: "mi", name: "Maori" },
  { code: "mr", name: "Marathi" },
  { code: "mh", name: "Marshallese" },
  { code: "ro", name: "Moldovan, Moldavian, Romanian" },
  { code: "mn", name: "Mongolian" },
  { code: "na", name: "Nauru" },
  { code: "nv", name: "Navajo, Navaho" },
  { code: "nd", name: "Northern Ndebele" },
  { code: "ng", name: "Ndonga" },
  { code: "ne", name: "Nepali" },
  { code: "se", name: "Northern Sami" },
  { code: "no", name: "Norwegian" },
  { code: "nb", name: "Norwegian Bokmål" },
  { code: "nn", name: "Norwegian Nynorsk" },
  { code: "ii", name: "Nuosu, Sichuan Yi" },
  { code: "oc", name: "Occitan (post 1500)" },
  { code: "oj", name: "Ojibwa" },
  { code: "or", name: "Oriya" },
  { code: "om", name: "Oromo" },
  { code: "os", name: "Ossetian, Ossetic" },
  { code: "pi", name: "Pali" },
  { code: "pa", name: "Panjabi, Punjabi" },
  { code: "ps", name: "Pashto, Pushto" },
  { code: "fa", name: "Persian" },
  { code: "pl", name: "Polish" },
  { code: "pt", name: "Portuguese" },
  { code: "qu", name: "Quechua" },
  { code: "rm", name: "Romansh" },
  { code: "rn", name: "Rundi" },
  { code: "ru", name: "Russian" },
  { code: "sm", name: "Samoan" },
  { code: "sg", name: "Sango" },
  { code: "sa", name: "Sanskrit" },
  { code: "sc", name: "Sardinian" },
  { code: "sr", name: "Serbian" },
  { code: "sn", name: "Shona" },
  { code: "sd", name: "Sindhi" },
  { code: "si", name: "Sinhala, Sinhalese" },
  { code: "sk", name: "Slovak" },
  { code: "sl", name: "Slovenian" },
  { code: "so", name: "Somali" },
  { code: "st", name: "Sotho, Southern" },
  { code: "nr", name: "South Ndebele" },
  { code: "es", name: "Spanish, Castilian" },
  { code: "su", name: "Sundanese" },
  { code: "sw", name: "Swahili" },
  { code: "ss", name: "Swati" },
  { code: "sv", name: "Swedish" },
  { code: "tl", name: "Tagalog" },
  { code: "ty", name: "Tahitian" },
  { code: "tg", name: "Tajik" },
  { code: "ta", name: "Tamil" },
  { code: "tt", name: "Tatar" },
  { code: "te", name: "Telugu" },
  { code: "th", name: "Thai" },
  { code: "bo", name: "Tibetan" },
  { code: "ti", name: "Tigrinya" },
  { code: "to", name: "Tonga (Tonga Islands)" },
  { code: "ts", name: "Tsonga" },
  { code: "tn", name: "Tswana" },
  { code: "tr", name: "Turkish" },
  { code: "tk", name: "Turkmen" },
  { code: "tw", name: "Twi" },
  { code: "ug", name: "Uighur, Uyghur" },
  { code: "uk", name: "Ukrainian" },
  { code: "ur", name: "Urdu" },
  { code: "uz", name: "Uzbek" },
  { code: "ve", name: "Venda" },
  { code: "vi", name: "Vietnamese" },
  { code: "vo", name: "Volap_k" },
  { code: "wa", name: "Walloon" },
  { code: "cy", name: "Welsh" },
  { code: "fy", name: "Western Frisian" },
  { code: "wo", name: "Wolof" },
  { code: "xh", name: "Xhosa" },
  { code: "yi", name: "Yiddish" },
  { code: "yo", name: "Yoruba" },
  { code: "za", name: "Zhuang, Chuang" },
  { code: "zu", name: "Zulu" },
];

export const social_account_icons = {
  twitter: (
    <BsTwitter
      style={{
        width: "22px",
        height: "22px",
        display: "inline-block",
      }}
    />
  ),
  instagram: (
    <BsInstagram
      style={{
        width: "22px",
        height: "22px",
        display: "inline-block",
      }}
    />
  ),
  facebook: (
    <BsFacebook
      style={{
        width: "22px",
        height: "22px",
        display: "inline-block",
      }}
    />
  ),
};

export const social_account_colors = {
  twitter: { background: "#1D9BF0", color: "white" },
  instagram: {
    background:
      "radial-gradient(circle farthest-corner at 35% 90%, #fec564, transparent 50%), radial-gradient(circle farthest-corner at 0 140%, #fec564, transparent 50%), radial-gradient(ellipse farthest-corner at 0 -25%, #5258cf, transparent 50%), radial-gradient(ellipse farthest-corner at 20% -50%, #5258cf, transparent 50%), radial-gradient(ellipse farthest-corner at 100% 0, #893dc2, transparent 50%), radial-gradient(ellipse farthest-corner at 60% -20%, #893dc2, transparent 50%), radial-gradient(ellipse farthest-corner at 100% 100%, #d9317a, transparent), linear-gradient(#6559ca, #bc318f 30%, #e33f5f 50%, #f77638 70%, #fec66d 100%)",
    color: "white",
  },
  facebook: {
    background: "#1877f2",
    color: "white",
  },
};

export const DesignTypes = [
  "A4 Document",
  "Annoucement",
  "Birthday Card",
  "Birthday invitation",
  "Blog Banner",
  "Book Cover",
  "Bookmark",
  "Broucher",
  "Business Card",
  "Calender",
  "Card",
  "Certificate",
  "Desktop Wallpaper",
  "Email Header",
  "Etsy Stop Cover",
  "Etsy Shop Icon",
  "Facebook ad",
  "Facebook App ad",
  "Facebook Cover",
  "Facebook Event Cover",
  "Facebook Post",
  "Flyer",
  "Gift Certificate",
  "Infographic",
  "Instagram Post",
  "Instagram Story",
  "Invitation",
  "Invoice",
  "Label",
  "Large Rectangle Ad",
  "Leaderboard Ad",
  "Lesson Plan",
  "Letter",
  "Linkedn Banner",
  "Logo",
  "Magazine Cover",
  "Medium Rectangle Ad",
  "Menu",
  "Mind Map",
  "Newsletter",
  "Photo Collage",
  "Pinterst Graphic",
  "Postcard",
  "Poster",
  "Presentation (16:9)",
  "Presentation (4:3)",
  "Product Label",
  "Recipe Card",
  "Resume",
  "Snapchat Geofilter",
  "Social Media Post",
  "Ticket",
  "Tumblr Graphic",
  "Twitter Header",
  "Twitter Post",
  "Wattpad Book Cover",
  "Wide Skyscraper Ad",
  "Worksheet",
  "Yearbook",
  "YouTube Channel Art",
  "YouTube Thumbnail",
];

export const cssValuesMonday = [
  {
    day: "monday",
    time: "00",
    "0-1 value": 0.05,
  },
  {
    day: "monday",
    time: "01",
    "0-1 value": 0.05,
  },
  {
    day: "monday",
    time: "02",
    "0-1 value": 0.05,
  },
  {
    day: "monday",
    time: "03",
    "0-1 value": 0.05,
  },
  {
    day: "monday",
    time: "04",
    "0-1 value": 0.1,
  },
  {
    day: "monday",
    time: "05",
    "0-1 value": 0.1,
  },
  {
    day: "monday",
    time: "06",
    "0-1 value": 0.2,
  },
  {
    day: "monday",
    time: "07",
    "0-1 value": 0.4,
  },
  {
    day: "monday",
    time: "08",
    "0-1 value": 0.5,
  },
  {
    day: "monday",
    time: "09",
    "0-1 value": 0.8,
  },
  {
    day: "monday",
    time: "10",
    "0-1 value": 0.8,
  },
  {
    day: "monday",
    time: "11",
    "0-1 value": 0.8,
  },
  {
    day: "monday",
    time: "12",
    "0-1 value": 0.8,
  },
  {
    day: "monday",
    time: "13",
    "0-1 value": 0.8,
  },
  {
    day: "monday",
    time: "14",
    "0-1 value": 0.6,
  },
  {
    day: "monday",
    time: "15",
    "0-1 value": 0.6,
  },
  {
    day: "monday",
    time: "16",
    "0-1 value": 0.6,
  },
  {
    day: "monday",
    time: "17",
    "0-1 value": 0.4,
  },
  {
    day: "monday",
    time: "18",
    "0-1 value": 0.4,
  },
  {
    day: "monday",
    time: "19",
    "0-1 value": 0.4,
  },
  {
    day: "monday",
    time: "20",
    "0-1 value": 0.6,
  },
  {
    day: "monday",
    time: "21",
    "0-1 value": 0.4,
  },
  {
    day: "monday",
    time: "22",
    "0-1 value": 0.25,
  },
  {
    day: "monday",
    time: "23",
    "0-1 value": 0.15,
  },
];

export const cssValuesTuesday = [
  {
    day: "Tuesday",
    time: "00",
    "0-1 value": 0.05,
  },
  {
    day: "Tuesday",
    time: "01",
    "0-1 value": 0.05,
  },
  {
    day: "Tuesday",
    time: "02",
    "0-1 value": 0.05,
  },
  {
    day: "Tuesday",
    time: "03",
    "0-1 value": 0.1,
  },
  {
    day: "Tuesday",
    time: "04",
    "0-1 value": 0.1,
  },
  {
    day: "Tuesday",
    time: "05",
    "0-1 value": 0.2,
  },
  {
    day: "Tuesday",
    time: "06",
    "0-1 value": 0.2,
  },
  {
    day: "Tuesday",
    time: "07",
    "0-1 value": 0.4,
  },
  {
    day: "Tuesday",
    time: "08",
    "0-1 value": 0.6,
  },
  {
    day: "Tuesday",
    time: "09",
    "0-1 value": 1,
  },
  {
    day: "Tuesday",
    time: "10",
    "0-1 value": 1,
  },
  {
    day: "Tuesday",
    time: "11",
    "0-1 value": 1,
  },
  {
    day: "Tuesday",
    time: "12",
    "0-1 value": 1,
  },
  {
    day: "Tuesday",
    time: "13",
    "0-1 value": 0.8,
  },
  {
    day: "Tuesday",
    time: "14",
    "0-1 value": 0.8,
  },
  {
    day: "Tuesday",
    time: "15",
    "0-1 value": 0.6,
  },
  {
    day: "Tuesday",
    time: "16",
    "0-1 value": 0.6,
  },
  {
    day: "Tuesday",
    time: "17",
    "0-1 value": 0.6,
  },
  {
    day: "Tuesday",
    time: "18",
    "0-1 value": 0.6,
  },
  {
    day: "Tuesday",
    time: "19",
    "0-1 value": 0.6,
  },
  {
    day: "Tuesday",
    time: "20",
    "0-1 value": 0.6,
  },
  {
    day: "Tuesday",
    time: "21",
    "0-1 value": 0.6,
  },
  {
    day: "Tuesday",
    time: "22",
    "0-1 value": 0.25,
  },
  {
    day: "Tuesday",
    time: "23",
    "0-1 value": 0.15,
  },
];

export const cssValuesWednesday = [
  {
    day: "Wednesday",
    time: "00",
    "0-1 value": 0.05,
  },
  {
    day: "Wednesday",
    time: "01",
    "0-1 value": 0.1,
  },
  {
    day: "Wednesday",
    time: "02",
    "0-1 value": 0.05,
  },
  {
    day: "Wednesday",
    time: "03",
    "0-1 value": 0.1,
  },
  {
    day: "Wednesday",
    time: "04",
    "0-1 value": 0.1,
  },
  {
    day: "Wednesday",
    time: "05",
    "0-1 value": 0.2,
  },
  {
    day: "Wednesday",
    time: "06",
    "0-1 value": 0.4,
  },
  {
    day: "Wednesday",
    time: "07",
    "0-1 value": 0.4,
  },
  {
    day: "Wednesday",
    time: "08",
    "0-1 value": 0.8,
  },
  {
    day: "Wednesday",
    time: "09",
    "0-1 value": 1,
  },
  {
    day: "Wednesday",
    time: "10",
    "0-1 value": 1,
  },
  {
    day: "Wednesday",
    time: "11",
    "0-1 value": 1,
  },
  {
    day: "Wednesday",
    time: "12",
    "0-1 value": 1,
  },
  {
    day: "Wednesday",
    time: "13",
    "0-1 value": 1,
  },
  {
    day: "Wednesday",
    time: "14",
    "0-1 value": 1,
  },
  {
    day: "Wednesday",
    time: "15",
    "0-1 value": 1,
  },
  {
    day: "Wednesday",
    time: "16",
    "0-1 value": 0.8,
  },
  {
    day: "Wednesday",
    time: "17",
    "0-1 value": 0.8,
  },
  {
    day: "Wednesday",
    time: "18",
    "0-1 value": 0.6,
  },
  {
    day: "Wednesday",
    time: "19",
    "0-1 value": 0.6,
  },
  {
    day: "Wednesday",
    time: "20",
    "0-1 value": 0.6,
  },
  {
    day: "Wednesday",
    time: "21",
    "0-1 value": 0.4,
  },
  {
    day: "Wednesday",
    time: "22",
    "0-1 value": 0.25,
  },
  {
    day: "Wednesday",
    time: "23",
    "0-1 value": 0.15,
  },
];

export const cssValuesThursday = [
  {
    day: "Thursday",
    time: "00",
    "0-1 value": 0.05,
  },
  {
    day: "Thursday",
    time: "01",
    "0-1 value": 0.05,
  },
  {
    day: "Thursday",
    time: "02",
    "0-1 value": 0.05,
  },
  {
    day: "Thursday",
    time: "03",
    "0-1 value": 0.1,
  },
  {
    day: "Thursday",
    time: "04",
    "0-1 value": 0.1,
  },
  {
    day: "Thursday",
    time: "05",
    "0-1 value": 0.1,
  },
  {
    day: "Thursday",
    time: "06",
    "0-1 value": 0.2,
  },
  {
    day: "Thursday",
    time: "07",
    "0-1 value": 0.4,
  },
  {
    day: "Thursday",
    time: "08",
    "0-1 value": 0.6,
  },
  {
    day: "Thursday",
    time: "09",
    "0-1 value": 1,
  },
  {
    day: "Thursday",
    time: "10",
    "0-1 value": 1,
  },
  {
    day: "Thursday",
    time: "11",
    "0-1 value": 1,
  },
  {
    day: "Thursday",
    time: "12",
    "0-1 value": 0.8,
  },
  {
    day: "Thursday",
    time: "13",
    "0-1 value": 0.8,
  },
  {
    day: "Thursday",
    time: "14",
    "0-1 value": 0.6,
  },
  {
    day: "Thursday",
    time: "15",
    "0-1 value": 0.6,
  },
  {
    day: "Thursday",
    time: "16",
    "0-1 value": 0.6,
  },
  {
    day: "Thursday",
    time: "17",
    "0-1 value": 0.6,
  },
  {
    day: "Thursday",
    time: "18",
    "0-1 value": 0.6,
  },
  {
    day: "Thursday",
    time: "19",
    "0-1 value": 0.6,
  },
  {
    day: "Thursday",
    time: "20",
    "0-1 value": 0.6,
  },
  {
    day: "Thursday",
    time: "21",
    "0-1 value": 0.4,
  },
  {
    day: "Thursday",
    time: "22",
    "0-1 value": 0.25,
  },
  {
    day: "Thursday",
    time: "23",
    "0-1 value": 0.15,
  },
];

export const cssValuesFriday = [
  {
    day: "Friday",
    time: "00",
    "0-1 value": 0.1,
  },
  {
    day: "Friday",
    time: "01",
    "0-1 value": 0.05,
  },
  {
    day: "Friday",
    time: "02",
    "0-1 value": 0.05,
  },
  {
    day: "Friday",
    time: "03",
    "0-1 value": 0.1,
  },
  {
    day: "Friday",
    time: "04",
    "0-1 value": 0.1,
  },
  {
    day: "Friday",
    time: "05",
    "0-1 value": 0.25,
  },
  {
    day: "Friday",
    time: "06",
    "0-1 value": 0.3,
  },
  {
    day: "Friday",
    time: "07",
    "0-1 value": 0.4,
  },
  {
    day: "Friday",
    time: "08",
    "0-1 value": 0.5,
  },
  {
    day: "Friday",
    time: "09",
    "0-1 value": 1,
  },
  {
    day: "Friday",
    time: "10",
    "0-1 value": 0.8,
  },
  {
    day: "Friday",
    time: "11",
    "0-1 value": 1,
  },
  {
    day: "Friday",
    time: "12",
    "0-1 value": 0.8,
  },
  {
    day: "Friday",
    time: "13",
    "0-1 value": 0.8,
  },
  {
    day: "Friday",
    time: "14",
    "0-1 value": 0.6,
  },
  {
    day: "Friday",
    time: "15",
    "0-1 value": 0.6,
  },
  {
    day: "Friday",
    time: "16",
    "0-1 value": 0.4,
  },
  {
    day: "Friday",
    time: "17",
    "0-1 value": 0.4,
  },
  {
    day: "Friday",
    time: "18",
    "0-1 value": 0.25,
  },
  {
    day: "Friday",
    time: "19",
    "0-1 value": 0.25,
  },
  {
    day: "Friday",
    time: "20",
    "0-1 value": 0.25,
  },
  {
    day: "Friday",
    time: "21",
    "0-1 value": 0.25,
  },
  {
    day: "Friday",
    time: "22",
    "0-1 value": 0.15,
  },
  {
    day: "Friday",
    time: "23",
    "0-1 value": 0.15,
  },
];

export const cssValuesSaturday = [
  {
    day: "Saturday",
    time: "00",
    "0-1 value": 0.05,
  },
  {
    day: "Saturday",
    time: "01",
    "0-1 value": 0.05,
  },
  {
    day: "Saturday",
    time: "02",
    "0-1 value": 0.05,
  },
  {
    day: "Saturday",
    time: "03",
    "0-1 value": 0.05,
  },
  {
    day: "Saturday",
    time: "04",
    "0-1 value": 0.05,
  },
  {
    day: "Saturday",
    time: "05",
    "0-1 value": 0.05,
  },
  {
    day: "Saturday",
    time: "06",
    "0-1 value": 0.1,
  },
  {
    day: "Saturday",
    time: "07",
    "0-1 value": 0.2,
  },
  {
    day: "Saturday",
    time: "08",
    "0-1 value": 0.4,
  },
  {
    day: "Saturday",
    time: "09",
    "0-1 value": 0.5,
  },
  {
    day: "Saturday",
    time: "10",
    "0-1 value": 0.5,
  },
  {
    day: "Saturday",
    time: "11",
    "0-1 value": 0.5,
  },
  {
    day: "Saturday",
    time: "12",
    "0-1 value": 0.4,
  },
  {
    day: "Saturday",
    time: "13",
    "0-1 value": 0.4,
  },
  {
    day: "Saturday",
    time: "14",
    "0-1 value": 0.4,
  },
  {
    day: "Saturday",
    time: "15",
    "0-1 value": 0.2,
  },
  {
    day: "Saturday",
    time: "16",
    "0-1 value": 0.2,
  },
  {
    day: "Saturday",
    time: "17",
    "0-1 value": 0.2,
  },
  {
    day: "Saturday",
    time: "18",
    "0-1 value": 0.2,
  },
  {
    day: "Saturday",
    time: "19",
    "0-1 value": 0.2,
  },
  {
    day: "Saturday",
    time: "20",
    "0-1 value": 0.2,
  },
  {
    day: "Saturday",
    time: "21",
    "0-1 value": 0.2,
  },
  {
    day: "Saturday",
    time: "22",
    "0-1 value": 0.15,
  },
  {
    day: "Saturday",
    time: "23",
    "0-1 value": 0.05,
  },
];

export const cssValuesSunday = [
  {
    day: "Sunday",
    time: "00",
    "0-1 value": 0.05,
  },
  {
    day: "Sunday",
    time: "01",
    "0-1 value": 0.05,
  },
  {
    day: "Sunday",
    time: "02",
    "0-1 value": 0.05,
  },
  {
    day: "Sunday",
    time: "03",
    "0-1 value": 0.05,
  },
  {
    day: "Sunday",
    time: "04",
    "0-1 value": 0.05,
  },
  {
    day: "Sunday",
    time: "05",
    "0-1 value": 0.05,
  },
  {
    day: "Sunday",
    time: "06",
    "0-1 value": 0.1,
  },
  {
    day: "Sunday",
    time: "07",
    "0-1 value": 0.2,
  },
  {
    day: "Sunday",
    time: "08",
    "0-1 value": 0.4,
  },
  {
    day: "Sunday",
    time: "09",
    "0-1 value": 0.5,
  },
  {
    day: "Sunday",
    time: "10",
    "0-1 value": 0.6,
  },
  {
    day: "Sunday",
    time: "11",
    "0-1 value": 0.6,
  },
  {
    day: "Sunday",
    time: "12",
    "0-1 value": 0.8,
  },
  {
    day: "Sunday",
    time: "13",
    "0-1 value": 0.6,
  },
  {
    day: "Sunday",
    time: "14",
    "0-1 value": 0.4,
  },
  {
    day: "Sunday",
    time: "15",
    "0-1 value": 0.4,
  },
  {
    day: "Sunday",
    time: "16",
    "0-1 value": 0.4,
  },
  {
    day: "Sunday",
    time: "17",
    "0-1 value": 0.2,
  },
  {
    day: "Sunday",
    time: "18",
    "0-1 value": 0.4,
  },
  {
    day: "Sunday",
    time: "19",
    "0-1 value": 0.4,
  },
  {
    day: "Sunday",
    time: "20",
    "0-1 value": 0.4,
  },
  {
    day: "Sunday",
    time: "21",
    "0-1 value": 0.4,
  },
  {
    day: "Sunday",
    time: "22",
    "0-1 value": 0.15,
  },
  {
    day: "Sunday",
    time: "23",
    "0-1 value": 0.05,
  },
];

export const WeekDay = {
  Monday: cssValuesMonday,
  Tuesday: cssValuesTuesday,
  Wednesday: cssValuesWednesday,
  Thursday: cssValuesThursday,
  Friday: cssValuesFriday,
  Saturday: cssValuesSaturday,
  Sunday: cssValuesSunday,
};

const getRandomColor = () => {
  var letters = "0123456789ABCDEF";
  var color = "#";
  for (var i = 0; i < 6; i++) {
    color += letters[Math.floor(Math.random() * 16)];
  }
  return color;
};

export const ministries = [
  {
    mediaUnit: "All India Radio",
    displayURL:
      "https://prasarbharati.gov.in/wp-content/uploads/2020/08/PB-NEW-LOGO-01-1.png",
    color: getRandomColor(),
  },
  {
    mediaUnit: "New Media Wing",
    displayURL:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpAYLAJfOGczSSy3VB6CFgiPt6XaZa5NeD3s5IyyuzGsF6zCDFUouoph_3QY84YMKDYwY&usqp=CAU",
    color: getRandomColor(),
  },
  {
    mediaUnit: "Bureau of Outreach and communication",
    displayURL:
      "https://yt3.ggpht.com/3We4nUrphNb7SpQzvbsp5uZt3_QbN_0Ioxj6BMnktOrKVk-3e2opQ-84X3u465JYBaNferzRYtM=s900-c-k-c0x00ffffff-no-rj",
    color: getRandomColor(),
  },
  {
    mediaUnit: "Publications Division",
    displayURL:
      "https://media.9curry.com/uploads/organization/image/2426/Publications_Division_Logo.png",
    color: getRandomColor(),
  },
  {
    mediaUnit: "Press Information Bureau",
    displayURL:
      "https://previews.123rf.com/images/grandeduc/grandeduc1509/grandeduc150900128/44445147-press-conference-3d-render-of-speaker-podium-with-microphones-and-blue-curtain-background.jpg",
    color: getRandomColor(),
  },
  {
    mediaUnit: "DD News",
    displayURL:
      "https://www.schools360.in/wp-content/uploads/2019/06/dd-news.jpg",
    color: getRandomColor(),
  },
];

export const languagesList = {
  auto: "Automatic",
  af: "Afrikaans",
  sq: "Albanian",
  am: "Amharic",
  ar: "Arabic",
  hy: "Armenian",
  az: "Azerbaijani",
  eu: "Basque",
  be: "Belarusian",
  bn: "Bengali",
  bs: "Bosnian",
  bg: "Bulgarian",
  ca: "Catalan",
  ceb: "Cebuano",
  ny: "Chichewa",
  "zh-cn": "Chinese Simplified",
  "zh-tw": "Chinese Traditional",
  co: "Corsican",
  hr: "Croatian",
  cs: "Czech",
  da: "Danish",
  nl: "Dutch",
  en: "English",
  eo: "Esperanto",
  et: "Estonian",
  tl: "Filipino",
  fi: "Finnish",
  fr: "French",
  fy: "Frisian",
  gl: "Galician",
  ka: "Georgian",
  de: "German",
  el: "Greek",
  gu: "Gujarati",
  ht: "Haitian Creole",
  ha: "Hausa",
  haw: "Hawaiian",
  iw: "Hebrew",
  hi: "Hindi",
  hmn: "Hmong",
  hu: "Hungarian",
  is: "Icelandic",
  ig: "Igbo",
  id: "Indonesian",
  ga: "Irish",
  it: "Italian",
  ja: "Japanese",
  jw: "Javanese",
  kn: "Kannada",
  kk: "Kazakh",
  km: "Khmer",
  ko: "Korean",
  ku: "Kurdish (Kurmanji)",
  ky: "Kyrgyz",
  lo: "Lao",
  la: "Latin",
  lv: "Latvian",
  lt: "Lithuanian",
  lb: "Luxembourgish",
  mk: "Macedonian",
  mg: "Malagasy",
  ms: "Malay",
  ml: "Malayalam",
  mt: "Maltese",
  mi: "Maori",
  mr: "Marathi",
  mn: "Mongolian",
  my: "Myanmar (Burmese)",
  ne: "Nepali",
  no: "Norwegian",
  ps: "Pashto",
  fa: "Persian",
  pl: "Polish",
  pt: "Portuguese",
  ma: "Punjabi",
  ro: "Romanian",
  ru: "Russian",
  sm: "Samoan",
  gd: "Scots Gaelic",
  sr: "Serbian",
  st: "Sesotho",
  sn: "Shona",
  sd: "Sindhi",
  si: "Sinhala",
  sk: "Slovak",
  sl: "Slovenian",
  so: "Somali",
  es: "Spanish",
  su: "Sundanese",
  sw: "Swahili",
  sv: "Swedish",
  tg: "Tajik",
  ta: "Tamil",
  te: "Telugu",
  th: "Thai",
  tr: "Turkish",
  uk: "Ukrainian",
  ur: "Urdu",
  uz: "Uzbek",
  vi: "Vietnamese",
  cy: "Welsh",
  xh: "Xhosa",
  yi: "Yiddish",
  yo: "Yoruba",
  zu: "Zulu",
};
